python get_feature.py \
  --load_model_path  "/media/dsg3/xuyitao/Face/model/params_res50IR_cos_CA.pkl" \
  --load_margin_path  "/media/dsg3/xuyitao/Face/model/margin_res50IR_cos_CA.pkl" \
  --save_model_path  "/media/dsg3/xuyitao/Face/model/params_res50IR_cos_CA.pkl"
  --save_margin_path  "/media/dsg3/xuyitao/Face/model/margin_res50IR_cos_CA.pkl" \
  --train_data_root "/media/dsg3/datasets/CASIA_WebFace/CASIA_align/" \
  --train_data_list "/home/dsg/xuyitao/Face/FaceTrain/CASIA_list.txt" \
  --train_data_fail "/home/dsg/xuyitao/Face/FaceTrain/CASIA_fail.txt" \
  --train_dataset "CASIA"
  --lr 0.05 \
  --batchsize 64 \
  --epoch 6666 \
  --attack "pgd"